require("carnifx.core.colorscheme")
require("carnifx.core.keymaps")
require("carnifx.core.options")
require("carnifx.plugins.lsp.lspconfig")
require("carnifx.plugins.lsp.mason")
require("carnifx.plugins.lsp.null-ls")
-- require("carnifx.plugins.lsp.lspsaga")
require("carnifx.plugins.autopairs")
require("carnifx.plugins.comment")
require("carnifx.plugins.gitsigns")
require("carnifx.plugins.lualine")
require("carnifx.plugins.nvim-cmp")
require("carnifx.plugins.nvim-tree")
require("carnifx.plugins.telescope")
require("carnifx.plugins.treesitter")
require("carnifx.plugins-setup")
